version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen_app_sia1
    ports:
      - "8000:80" # Web access
      - "2223:22" # SSH access
    volumes:
      - ./laravel:/var/www/html  # Changed from laravel to lumen
      - ./php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: sia1_db
    ports:
      - "3308:3306"  # Changed to match your DB_PORT
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: Pailanan  # Matches your DB_DATABASE
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lumen_phpmyadmin_sia1
    ports:
      - "8080:80"
    environment:
      PMA_HOST: sia1_db
    depends_on:
      - db

volumes:
  dbdata: